name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo apt update
          sudo apt install libgtk-3-dev libsdl2-dev -y
          pip3 install build wheel attrdict3
          pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          pip3 install -r requirements.txt
      
      - name: Build
        run: |
          python3 -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WallChange_Wheels
          path: dist/
